mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from scheduler import views

urlpatterns = [
    path('', include('scheduler.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

scheduler/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from . import views


urlpatterns = [
    path('', views.indexView, name="index_view"),
    path('rest-auth/google/', views.GoogleLogin.as_view(), name='redirect'),
    path('createclass', views.StudentClassCreateView.as_view(), name='create_student_class'),
    path('listclasses/', views.StudentClassListView.as_view(), name = 'list_student_classes'),
    path('joinclass/', views.joinclassView, name = 'join_student_classes'),
    path('listclasses/removeclass/<int:pk>/', views.remove_class, name = 'delete_student_class'),
    path('joinclass/allclasses', views.JoinClassListView.as_view(), name= 'all_classes'),
    path('todo/', views.todoAppView, name='todo'),
    path('addTodoItem/', views.addTodoView),
    path('deleteTodoItem/<int:i>/', views.deleteTodoView),
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/<int:event_id>/', views.event, name='event_edit'),
    path('class/<int:pk>/', views.ClassView.as_view(), name="class_detail"),
    path('j_class/<int:pk>/', views.JoinClassView.as_view(), name="join_class_detail"),
    path('j_class/', views.ClassSearch, name="class_search"),
    path('j_class/search/<str:instructor>', views.JoinClassFilterView.as_view(), name="filtered_classes"),
    path('j_class/<int:pk>/addjoin/', views.add_join_class, name="add_join"),
    path('class/<int:pk>/addnote/', views.AddNote, name = 'class_add_note'),
    path('class/<int:pk>/deletenote/<int:id>', views.DeleteNote, name = 'class_delete_note'),
    path('rooms', views.all_rooms, name="all_rooms"),
    url(r'token$', views.token, name="token"),
    url(r'rooms/(?P<slug>[-\w]+)/$', views.room_detail, name="room_detail"),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

scheduler/models.py
########################################################################################
#  REFERENCES
#
#  Title: How to Extend Django User Model
#  Author: Vitor Freitas
#  Date: 7/22/2016
#  URL: https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
#  Software License: <license software is released under>
#
#  Title: django-multiselectfield
#  Author: blag, Goin, tomasgarzon
#  Date: 2/20/2020
#  Code version: 0.1.12
#  URL: https://pypi.org/project/django-multiselectfield/
#  Software License:
#
#  Title: How to Create a To-do List App Using Django
#  Author: Ashwin Joy
#  URL: https://pythonistaplanet.com/to-do-list-app-using-django/
#
#  Title: cal/models.py
#  Author: Hui Wen
#  Date: 7/24/2018
#  URL: https://www.huiwenteo.com/normal/2018/07/24/django-calendar.html
#
#  Title: cal/models.py
#  Author: Hui Wen
#  Date: 7/29/2018
#  URL: https://www.huiwenteo.com/normal/2018/07/29/django-calendar-ii.html
#
#  Title: chat/models.py
#  Author: Kevin Ndung'u
#  Date: 5/15/2018
#  URL: https://www.twilio.com/blog/2018/05/build-chat-python-django-applications-programmable-chat.html
########################################################################################


from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from multiselectfield import MultiSelectField
import datetime



# Create your models here.

# Profile model, an extension of the built-in Django user model
# Used to keep track of additional information about the user
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name = "profile", null=True)

	# To retrieve the list of classes the user is enrolled in, call self.studentclass_set.all()

	def __str__(self):
		return self.user.username

# Signal function that automatically creates a corresponding instance of a Profile model whenever an instance of a User model is created
# Reference: How to extend Django User Model, Vitor Freitas
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user = instance)

# Signal function that automatically creates a corresponding instance of a Profile model whenever an instance of a User model is created
# Reference: How to extend Django User Model by Vitor Freitas
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()

# NoteFile, a model for storing notes a user has uploaded for their classes
class NoteFile(models.Model):
	note = models.FileField()
	title = models.CharField(max_length=200, default='')
	upload_time = models.DateTimeField(auto_now=True)
	user = models.ManyToManyField(Profile)

	def __str__(self):
		return self.title


# StudentClass model, a model that contains information about courses users are enrolled in
# Reference: django-multiselectfield by blag et al.
class StudentClass(models.Model):
	class_name = models.CharField(max_length=200, default='')
	instructor = models.CharField(max_length=200, default='')
	users = models.ManyToManyField(Profile)
	start_time = models.TimeField(null=True)
	end_time = models.TimeField(null=True)
	location = models.CharField(max_length=200, default='')
	enrolled_users_count = models.IntegerField(default=0)
	notes = models.ManyToManyField(NoteFile)
	DAY_OF_THE_WEEK = (
		("Sunday", "Sunday"),
		("Monday", "Monday"),
		("Tuesday", "Tuesday"),
		("Wednesday", "Wednesday"),
		("Thursday", "Thursday"),
		("Friday", "Friday"),
		("Saturday", "Saturday"),
	)

	days_of_the_week = MultiSelectField(choices = DAY_OF_THE_WEEK)


	class Meta:
		verbose_name_plural = 'Student Classes'
		unique_together = [['class_name', 'instructor']]

	def __str__(self):
		return self.class_name


# TodoListItem model, a model representing a single task on a todolist
# Reference: How to Create a To-do List App Using Django by Ashwin Joy
class TodoListItem(models.Model):
    content = models.TextField()
    users = models.ManyToManyField(Profile)

    def __str__(self):
    	return self.content

# Event model, a model containing information about events the user has scheduled
# Reference: cals/views.py by Hui Wen
class Event(models.Model):
	title = models.CharField(max_length=200)
	description = models.TextField()
	start_time = models.DateTimeField()
	users = models.ManyToManyField(Profile)

	@property
	def get_html_url(self):
		url = reverse('event_edit', args=(self.id,))
		return f'<a href="{url}"> {self.title} </a>'

	def __str__(self):
		return self.title

# Room model, a model for storing details about each chat room
# Reference: chat/views.py by Kevin Ndung'u
class Room(models.Model):
    """Represents chat rooms that users can join"""
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    slug = models.CharField(max_length=50)

    def __str__(self):
        """Returns human-readable representation of the model instance."""
        return self.name

scheduler/views.py
########################################################################################
#  REFERENCES
#
#  Title: Getting started with Django social authentication
#  Author: Moeedlodhi
#  Date: 6/21/2021
#  URL: https://medium.com/geekculture/getting-started-with-django-social-authentication-80ee7dc26fe0
#
#  Title: How to Create a To-do List App Using Django
#  Author: Ashwin Joy
#  URL: https://pythonistaplanet.com/to-do-list-app-using-django/
#
#
#  Title: cal/views.py
#  Author: Hui Wen
#  Date: 7/24/2018
#  URL: https://www.huiwenteo.com/normal/2018/07/24/django-calendar.html
#
#  Title: cal/views.py
#  Author: Hui Wen
#  Date: 7/29/2018
#  URL: https://www.huiwenteo.com/normal/2018/07/29/django-calendar-ii.html
#
#  Title: Deleting An Event
#  Author: BenjaminAm
#  Date: 1/11/2021
#  URL: https://github.com/huiwenhw/django-calendar/issues/10
#
#  Title: chat/views.py
#  Author: Kevin Ndung'u
#  Date: 5/15/2018
#  URL: https://www.twilio.com/blog/2018/05/build-chat-python-django-applications-programmable-chat.html
########################################################################################

from django.contrib.auth.models import User
from django.db.models.fields import GenericIPAddressField
from django.conf import settings
from django.http import JsonResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse
from allauth.socialaccount.providers.google.views import GoogleOAuth2Adapter
from rest_auth.registration.views import SocialLoginView
from rest_framework import authentication, permissions
from rest_framework.views import APIView
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from scheduler.models import StudentClass, Profile, NoteFile, TodoListItem, Event, Room
from .utils import Calendar
from .forms import EventForm, JoinForm
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views import generic
from django.views.generic.list import ListView
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils.safestring import mark_safe
from datetime import datetime, timedelta, date
import calendar
from twilio.jwt.access_token import AccessToken
from twilio.jwt.access_token.grants import ChatGrant

# View for Google login page
# Reference: Getting started with Django social authentication by Moeedlodhi
class GoogleLogin(SocialLoginView):
    adapter_class = GoogleOAuth2Adapter

# Code for returning a token given the Google Access code
# Reference: Getting started with Django social authentication by Moeedlodhi
def post(self, request, *args, **kwargs):
        response = super(GoogleLogin, self).post(request, *args, **kwargs)
        token = Token.objects.get(key=response.data['key'])
        return Response({'token': token.key, 'id': token.user_id})

# View for home page
def indexView(request):
    if request.user.is_anonymous:
        return render(request, 'scheduler/index.html')
    return render(request, 'scheduler/index.html') 

# View for join class page
def joinclassView(request):
    return render(request, 'scheduler/joinclass.html')

# View for displaying TodoListItems the user has created
# Reference: How to Create a To-do List App Using Django by Ashwin Joy
def todoAppView(request):
    q1 = Profile.objects.filter(user=request.user)[0]
    user_todo_items = q1.todolistitem_set.all()
    return render(request, 'scheduler/todo.html', {'all_items':user_todo_items}) 

# View for adding TodoListItems
# Reference: How to Create a To-do List App Using Django by Ashwin Joy
def addTodoView(request):
    new_item = TodoListItem(content = request.POST['content'])
    if new_item.content.strip() != "":
        new_item.save()
        new_item.users.add(request.user.profile)
        new_item.save()
    return HttpResponseRedirect('/todo') 

# deleteTodoView, a function based view for deleting TodoListItems
# Reference: How to Create a To-do List App Using Django by Ashwin Joy
def deleteTodoView(request, i):
    todo_item = TodoListItem.objects.get(id=i)
    todo_item.delete()
    return HttpResponseRedirect('/todo')

# CalendarView, a view that takes all the events a user has submitted and returns it in calendar format
# Allows user to scroll between the current, previous, and next month
# Reference: cal/views.py by Hui Wen
class CalendarView(generic.ListView):
    model = Event
    template_name = 'scheduler/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month', None))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(self.request.user.profile, d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

    def get_queryset(self):
        q1 = Profile.objects.filter(user = self.request.user)[0]
        return q1.event_set.all()
        #return Event.objects.filter(users=self.request.user.profile)


# Helper function for CalendarView that returns a datetime object of the current day
# Reference: cal/views.py by Hui Wen
def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

# Helper function for CalendarView that, given a datetime object, returns the previous month
# Reference: cal/views.py by Hui Wen
def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

# Helper function for CalendarView that, given a datetime object, returns the next month
# Reference: cal/views.py by Hui Wen
def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

# View for displaying the event submission form and updates the Event model table based on user input
# References: cal/views.py by Hui Wen, Deleting an Event by BenjaminAm
def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
    
    form = EventForm(request.POST or None, instance=instance)


    # Delete functionality adapted from BejaminAm, 1/11/2021
    # https://github.com/huiwenhw/django-calendar/issues/10
    
    # if user presses the save button
    if request.POST and 'save' in request.POST and form.is_valid():
        instance.save()
        instance.users.add(request.user.profile)
        instance.save()
        form.save()
        return HttpResponseRedirect(reverse('calendar'))

    # if user presses the delete button
    if request.POST and 'delete' in request.POST:
        if event_id:
            Event.objects.filter(pk=event_id).delete()
            return HttpResponseRedirect(reverse('calendar'))

    return render(request, 'scheduler/event.html', {'form': form})

# View for adding a class to the system
@method_decorator(login_required(login_url='/accounts/google/login'), name='dispatch')
class StudentClassCreateView(CreateView):
    model = StudentClass
    fields = ['class_name', 'instructor', 'start_time', 'end_time', 'location', 'days_of_the_week']
    template_name = 'scheduler/createclass.html'
    success_url = '/listclasses'

    def clean(self):
        classes = StudentClass.objects.all()
        for c in classes:
            new = form.save(commit=False)
            if (new.class_name.strip().upper() == c.class_name.strip().upper() and new.instructor.strip().upper() == c.instructor.strip().upper() and \
                new.start_time == c.start_time and new.end_time == c.end_time):
                raise ValidationError(
            "The class you wish to add is already in the system. Please join this class through the \"Join Class\" page")
    
    # Form validation
    # Adapted from user zaidfazil, 9/23/2017
    # https://stackoverflow.com/questions/46378465/class-based-views-cbv-createview-and-request-user-with-a-many-to-many-relatio
    def form_valid(self, form):
        self.object = form.save()
        self.object.users.add(self.request.user.profile)
        self.object.enrolled_users_count += 1
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# View for displaying the list of all classes that can be joined
@method_decorator(login_required(login_url='/accounts/google/login'), name='dispatch')
class JoinClassListView(ListView):   
    model = StudentClass
    template_name = 'scheduler/all_classes.html'
    context_object_name = 'join_list_of_classes'
    success_url = '/listclasses'
    def get_queryset(self):
        return StudentClass.objects.all()

# View for join class page
class JoinClassView(DetailView):
    model = StudentClass
    template_name = 'scheduler/join.html'
    success_url = '/listclasses'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

# View for filtered join class page
class JoinClassFilterView(ListView):
    model = StudentClass
    template_name ='scheduler/filtered_classes.html'
    context_object_name = "list_of_classes"
    def get_queryset(self):
        return StudentClass.objects.filter(instructor__icontains = self.kwargs['instructor'])

scheduler/templates/scheduler/all_classes.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    {% if join_list_of_classes %}
    <h3 class="text-left" style = "color: white;"><br> List of all classes</h3>
    <h6 class="text-left" style = "color: white;" > Click on a blue link to see class information before joining.</h6>

    {% for class in join_list_of_classes %}
		
  		<div class="col-lg-3 d-flex align-items-stretch" style = "padding: 1em">
            <div class = 'card shadow w-100 border-dark'>
            	<div class = "card-body">
		
		<h4> 
		<a class="link-primary" href="{% url 'join_class_detail' class.id %}"> 
			{{class.class_name}}
		</a> 
		</h4> 

		<p class="text-dark"> 
			Instructor: {{class.instructor}} <br> Time: {{class.start_time}} - {{class.end_time}} <br> Location: {{class.location}} <br> Days: {{ class.days_of_the_week }}
       	</p>
       </div>
   </div>
</div>
       
    {% endfor %}
  
{% else %} 

    <h3 class="text-light"> <br> No Classes are available.</h3>  
{% endif %}
</div>
</div>
{% endblock %}

scheduler/templates/scheduler/calendar.html
<!-- 
	Template for displaying a user's calendar of events
	Adapted from Hui Wen, 7/24/2018 and 7/29/2018
	URLs: https://www.huiwenteo.com/normal/2018/07/24/django-calendar.html and https://www.huiwenteo.com/normal/2018/07/29/django-calendar-ii.html
-->

{% extends "scheduler/calendar_base.html" %}

{% block content %}

{% include "base.html" %}

<div class="clearfix">
  <a class="btn btn-outline-light left" href="{% url 'calendar' %}?{{ prev_month }}"> Previous Month </a>
  <a class="btn btn-outline-light right" href="{% url 'calendar' %}?{{ next_month }}"> Next Month </a>
  <a class="btn btn-outline-light right" href="{% url 'event_new' %}"> New Event </a>
</div>


{{ calendar }}



{% endblock %}

scheduler/templates/scheduler/calendar_base.html
<!-- 
  Base template for the calendar web page. Contains links to relevant stylesheets
  Adapted from Hui Wen, 7/24/2018
  URL: https://www.huiwenteo.com/normal/2018/07/24/django-calendar.html 
-->

{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
  <!-- Bootstrap CSS -->
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
  <title>Calendar</title>
</head>

<body>

  {% block content %}
  {% endblock %}

</body>
</html>

scheduler/templates/scheduler/class.html
{% extends "base.html" %}


{% block content %}
<h1 class="text-center text-white m-3">{{ object.class_name }}</h1>

<div class="row w-100" data-masonry='{"percentPosition": true }'>

    <div class="col-6 d-flex justify-content-center">

        <div class="card w-75 text-center bg-light">
            <div class="card-body">
                <h4 class="card-title">Your Notes</h4>
                <form action="{% url 'class_add_note' object.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label class="form-label" for="formFile">Upload a .pdf file of your notes</label>
                    <br>
                    <input class="form-control-md" type="text" name="title" placeholder="Note Title (optional)">
                    <br>
                    <input class="form-control-md" type="file" accept=".pdf" id="formFile" name="noteFile" required>
                    <button type="submit" class="btn btn-primary btn-md btn-block">Submit note</button>
                </form>
                {% if files %}
                    <div class="text-center">
                    <ul class="list-group w-75" style="display: inline-block; text-align: left;">
                    {% for file in files%}
                        <li class="list-group-item">
                            <table>
                                <tr>
                                    <form action="{% url 'class_delete_note' file.id object.id%}" method = "post">{% csrf_token %}
                                    <input class= "btn btn-outline-danger btn-sm" type="submit" value="x" style="padding: 0.1vh 1vh 0.1vh 1vh;">
                                    </form> &emsp;
                                    <a href="{{ file.note.url }}" target="_blank">{{ file.title }}</a>
                                </tr>
                            </table>            
                        </li>
                    {% endfor %}
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>

    </div>

    <div class="col-6 d-flex justify-content-center">

        <div class="row justify-content-center">

        <div class="card w-75 text-center bg-light mb-3">
            <div class="card-body">
                <h4 class="card-title">Class Information</h4>
                <table class="table text-center">
                    <tr>
                        <td> <strong>Instructor</strong>: {{object.instructor}} </td>
                        <td> <strong>Location</strong>: {{object.location}} </td>
                    </tr>
                    <tr>
                        <td> <strong>Time</strong>: {{object.start_time}} - {{object.end_time}} </td>
                        <td> <strong>Class Size</strong>: {{object.enrolled_users_count}} </td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="card w-75 text-center bg-light">
            <div class="card-body">
                <h4 class="card-title">Your Classmates</h4>

                <ul class="list-group text-center">
                {% for classmate in classmates %}
                <li class="list-group-item">{{classmate}} (<a href="mailto:{{classmate.user.email}}">{{classmate.user.email}}</a>)</li>
                {% endfor %}
                </ul>

            </div>
        </div>

        </div>
        
    </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>

{% endblock %}

scheduler/templates/scheduler/createclass.html
<!--Template for testing social authentication adapted from Muhd Rahiman, 2/27/2021
    https://dev.to/mdrhmn/django-google-authentication-using-django-allauth-18f8-->
{% extends "base.html" %}

{% block content %}

<center>
<h1> </h1>
<div class="mt-lg-4">

<div class="container">
    	<h3 class="text-center" style = "color: white;">Add a Class</h6>
</div>

<div class="mt-lg-4" style="width: fit-content;">

{% if form.errors %}
    <p class="text-warning"><strong>The class you wish to add already exists. Please join this class by looking for it through our <a class="link-warning" href="{% url 'join_student_classes' %}">Join Class</a> page.</strong></p>
{% endif %}
<form method="post">{% csrf_token %}
    <!--{{ form.as_p }}-->
    <div class="row">
        <div class="col">
            <label for="id_class_name" style = "color: white;">Class Name:</label>
            <input class="form-control" id="id_class_name" type="text" name="class_name" maxlength="200" required>
        </div>
        
        <div class="col">
            <label for="id_instructor" style = "color: white;">Instructor:</label>
            <input class="form-control" id="id_instructor" type="text" name="instructor" maxlength="200" required>
        </div>
        <div class="col">
            <label for="id_location" style = "color: white;">Location:</label>
            <input class="form-control" id="id_location" type="text" name="location" maxlength="200" required>
        </div>
            
        </div>
        <div class="row">
            <div class="col">
                <label for="id_start_time" style = "color: white;">Start Time:</label>
                <input id="id_start_time" class="form-control" type="time" name="start_time" required>
            </div>
            <div class="col">
                <label for="id_end_time" style = "color: white;">End Time:</label>
                <input id="id_end_time" class="form-control" type="time" name="end_time" required>
            </div>

        </div>
        <br>
        <div class="row">
            <div class="col" style = "color: white;">
                Days of the Week: &emsp;
                {% for value, text in form.days_of_the_week.field.choices %}
            
                <input id="id_days_of_the_week_{{ forloop.counter0 }}" name="{{ form.days_of_the_week.name }}" type="checkbox" value="{{ value }}" {% if value in checked_days_of_the_week %} checked="checked"{% endif %}>
                <label>{{ text }}</label>
            
                {% endfor %}
            </div>
        </div>
    


    

    <br>

    <input class="btn btn-success" type="submit" value="Save Class">
</form>
</center>
{% endblock %}

scheduler/templates/scheduler/event.html
<!-- 
  Template for event submission form
  Adapted from Hui Wen, 7/29/2018
  URL: https://www.huiwenteo.com/normal/2018/07/29/django-calendar-ii.html
-->

{% extends "base.html" %}
{% block title %}Event{% endblock %}

{% block content %}

<div class="clearfix">
  <a class="btn btn-outline-light left m-2" href="{% url 'calendar' %}"> Calendar </a>
</div>

<div class="col d-flex justify-content-center text-white">
<form method="post">
  {% csrf_token %}
  <table class="form form-table" style = "color: white; border: white;">
    {{ form }}
    <!-- Delete functionality added by BenjaminAm on Github, https://github.com/huiwenhw/django-calendar/issues/10 -->
    <tr class="text-center">
      <td colspan="2">
        <br>
        <button type="submit" name="delete" class="btn btn-danger right"> Delete </button>
        <button type="submit" name="save" class="btn btn-dark right"> Submit </button>
      </td>
    </tr>
  </table>
</form>
</div>
{% endblock %}

scheduler/templates/scheduler/filtered_classes.html
{% extends "base.html" %}

{% block content %}

<br>
        {% if list_of_classes %}
        <div class="container">

            <div class="row">

            <h3 class="text-light">Search Results</h3>
            {% for class in list_of_classes %}
            <div class="col-lg-3 d-flex align-items-stretch" style = "padding: 1em">
                <div class = 'card shadow w-100 border-dark'>
                    <div class = "card-body">
            
            <h4> 
            <a class="link-primary" href="{% url 'join_class_detail' class.id %}"> 
                {{class.class_name}}
            </a> 
            </h4> 
    
            <p class="text-dark"> 
                Instructor: {{class.instructor}} <br> Time: {{class.start_time}} - {{class.end_time}} <br> Location: {{class.location}} <br> 
            </p>
        </div>
    </div>
</div>
            
            {% endfor %}
        <div class="col-lg-3 d-flex align-items-stretch" style = "padding: 1em">
                <div class = 'card shadow w-100 border-dark'>
                    <div class = "card-body">
            <h4> 
            
                <br>
                <br>
                <div class="text-center">
                    <a class="link-primary" href="/joinclass">Previous page</a>
                </div>
                <br>
                <br>
                <br>
    
            </a> 
            </h4> 
           
           </div>
    </div>
</div>
      
    {% else %} 
    <div class="container">
    <div class="row">
        <div class="col text-center">
            <br>
            <h3 class="text-light">No classes match your search. Please refine your search keyword or <a class="link-dark" href="{% url 'create_student_class'  %}">add a new class.</a></h3>  
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 d-flex align-items-stretch" style = "padding: 1em">
                <div class = 'card shadow w-100 border-dark'>
                    <div class = "card-body">
            <h4> 
            
                <br>
                <center>
                    Search again by instructor.
                </center>			
                <br>
                <br>
                <form action="{% url 'class_search' %}" method="post">
                    {% csrf_token %}
                    <!--<div style="float: left;">
                        <input class="form-control-sm" type="text" name="class_name" placeholder="Class Name">
                    </div>
                -->
                    <div class="text-center">
                        <input class="form-control-sm" type="text" name="instructor" placeholder="Instructor" required>
                    </div>
    
                    <br>
                    <div class="text-center">
                        <button class="btn btn-primary btn-md btn-block" type="submit">Search</button> 
                    </div>
                    
    
    
                </form>
                
                
                <br>
                <br>
                <br>
            </h4> 
          
            </div>
    </div> 
    {% endif %}
    </div>
    </div>
    {% endblock %}
    </div>
</div>